version: '2'
services: 
  graphite:
    image: paulkling/graphite-statsd
    restart: always
    ports:
      - "7000:8000"
      - "2003:2003"
      - "2004:2004"
    volumes:
      - "/data/graphite:/opt/graphite/storage/whisper"

  statsd:
    image: ennexa/statsd
    restart: always
    ports:
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - "/data/statsd:/etc/statsd"
    links:
      - graphite

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "/data/grafana:/var/lib/grafana"
    links:
      - graphite
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SERVER_ROOT_URL=http://us01dv2utl04
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource